package br.com.pacto.recrutamento.app.templatevaga;

import br.com.pacto.recrutamento.app.dtos.templatevaga.*; import br.com.pacto.recrutamento.app.dtos.vaga.VagaDTO; import br.com.pacto.recrutamento.app.services.TemplateVagaService; import br.com.pacto.recrutamento.core.common.TypedResponse; import br.com.pacto.recrutamento.core.entities.*;
import java.time.*; import java.util.*;

public class TemplateVagaServiceImpl implements TemplateVagaService {
 private final TemplateVagaRepositorio templates; private final PerguntaTemplateVagaRepositorio perguntas; private final RequisitoTemplateVagaRepositorio requisitos; private final VagaTemplateRepositorio vagas; private final PerguntaVagaTemplateRepositorio perguntasVaga; private final RequisitoVagaTemplateRepositorio requisitosVaga; private final AutorizacaoTemplateVaga autorizacao; private final Clock clock;
 public TemplateVagaServiceImpl(TemplateVagaRepositorio t,PerguntaTemplateVagaRepositorio p,RequisitoTemplateVagaRepositorio r,VagaTemplateRepositorio v,PerguntaVagaTemplateRepositorio pv,RequisitoVagaTemplateRepositorio rv,AutorizacaoTemplateVaga a,Clock c){templates=t;perguntas=p;requisitos=r;vagas=v;perguntasVaga=pv;requisitosVaga=rv;autorizacao=a;clock=c;}
 public TypedResponse<TemplateVagaDTO> criarTemplate(CriarTemplateVagaDTO c){if(c==null||c.getResponsavelId()==null||invalido(c.getTitulo())||invalido(c.getDescricao()))return erro(400,"Dados do template invalidos");if(!admin(c.getResponsavelId()))return erro(403,"Acesso nao autorizado");return template(201,"Template criado",templates.salvar(new TemplateVaga(c.getResponsavelId(),c.getTitulo(),c.getDescricao())));}
 public TypedResponse<TemplateVagaDTO> atualizarTemplate(AtualizarTemplateVagaDTO c){if(c==null||c.getTemplateId()==null||invalido(c.getTitulo())||invalido(c.getDescricao()))return erro(400,"Dados do template invalidos");if(!admin(c.getUsuarioSolicitanteId()))return erro(403,"Acesso nao autorizado");Optional<TemplateVaga> t=templates.buscarAtivoPorId(c.getTemplateId());if(!t.isPresent())return erro(404,"Template nao encontrado");t.get().setTitulo(c.getTitulo());t.get().setDescricao(c.getDescricao());return template(200,"Template atualizado",templates.salvar(t.get()));}
 public TypedResponse<Void> excluirTemplate(ExcluirItemTemplateVagaDTO c){if(c==null||c.getTemplateId()==null)return vazio(400,"Dados do template invalidos");if(!admin(c.getUsuarioSolicitanteId()))return vazio(403,"Acesso nao autorizado");Optional<TemplateVaga> t=templates.buscarAtivoPorId(c.getTemplateId());if(!t.isPresent())return vazio(404,"Template nao encontrado");t.get().setExcluidoEm(agora());templates.salvar(t.get());return vazio(204,"Template excluido");}
 public TypedResponse<PerguntaTemplateVagaDTO> criarPerguntaDoTemplate(SalvarPerguntaTemplateVagaDTO c){if(c==null||perguntaInvalida(c))return erroPergunta(400,"Dados da pergunta invalidos");if(!admin(c.getUsuarioSolicitanteId()))return erroPergunta(403,"Acesso nao autorizado");if(!templates.buscarAtivoPorId(c.getTemplateId()).isPresent())return erroPergunta(404,"Template nao encontrado");PerguntaTemplateVaga p=new PerguntaTemplateVaga();preencher(p,c);return pergunta(201,"Pergunta criada",perguntas.salvar(p));}
 public TypedResponse<PerguntaTemplateVagaDTO> atualizarPerguntaDoTemplate(SalvarPerguntaTemplateVagaDTO c){if(c==null||c.getPerguntaId()==null||perguntaInvalida(c))return erroPergunta(400,"Dados da pergunta invalidos");if(!admin(c.getUsuarioSolicitanteId()))return erroPergunta(403,"Acesso nao autorizado");if(!templates.buscarAtivoPorId(c.getTemplateId()).isPresent())return erroPergunta(404,"Template nao encontrado");Optional<PerguntaTemplateVaga> p=perguntas.buscarAtivaPorId(c.getPerguntaId());if(!p.isPresent()||!c.getTemplateId().equals(p.get().getTemplateVagaId()))return erroPergunta(404,"Pergunta nao encontrada");preencher(p.get(),c);return pergunta(200,"Pergunta atualizada",perguntas.salvar(p.get()));}
 public TypedResponse<Void> excluirPerguntaDoTemplate(ExcluirItemTemplateVagaDTO c){if(c==null||c.getTemplateId()==null||c.getItemId()==null)return vazio(400,"Dados da pergunta invalidos");if(!admin(c.getUsuarioSolicitanteId()))return vazio(403,"Acesso nao autorizado");if(!templates.buscarAtivoPorId(c.getTemplateId()).isPresent())return vazio(404,"Template nao encontrado");Optional<PerguntaTemplateVaga> p=perguntas.buscarAtivaPorId(c.getItemId());if(!p.isPresent()||!c.getTemplateId().equals(p.get().getTemplateVagaId()))return vazio(404,"Pergunta nao encontrada");p.get().setExcluidoEm(agora());perguntas.salvar(p.get());return vazio(204,"Pergunta excluida");}
 public TypedResponse<RequisitoTemplateVagaDTO> criarRequisitoDoTemplate(SalvarRequisitoTemplateVagaDTO c){if(c==null||requisitoInvalido(c))return erroRequisito(400,"Dados do requisito invalidos");if(!admin(c.getUsuarioSolicitanteId()))return erroRequisito(403,"Acesso nao autorizado");if(!templates.buscarAtivoPorId(c.getTemplateId()).isPresent())return erroRequisito(404,"Template nao encontrado");RequisitoTemplateVaga r=new RequisitoTemplateVaga();preencher(r,c);return requisito(201,"Requisito criado",requisitos.salvar(r));}
 public TypedResponse<RequisitoTemplateVagaDTO> atualizarRequisitoDoTemplate(SalvarRequisitoTemplateVagaDTO c){if(c==null||c.getRequisitoId()==null||requisitoInvalido(c))return erroRequisito(400,"Dados do requisito invalidos");if(!admin(c.getUsuarioSolicitanteId()))return erroRequisito(403,"Acesso nao autorizado");if(!templates.buscarAtivoPorId(c.getTemplateId()).isPresent())return erroRequisito(404,"Template nao encontrado");Optional<RequisitoTemplateVaga> r=requisitos.buscarAtivoPorId(c.getRequisitoId());if(!r.isPresent()||!c.getTemplateId().equals(r.get().getTemplateVagaId()))return erroRequisito(404,"Requisito nao encontrado");preencher(r.get(),c);return requisito(200,"Requisito atualizado",requisitos.salvar(r.get()));}
 public TypedResponse<Void> excluirRequisitoDoTemplate(ExcluirItemTemplateVagaDTO c){if(c==null||c.getTemplateId()==null||c.getItemId()==null)return vazio(400,"Dados do requisito invalidos");if(!admin(c.getUsuarioSolicitanteId()))return vazio(403,"Acesso nao autorizado");if(!templates.buscarAtivoPorId(c.getTemplateId()).isPresent())return vazio(404,"Template nao encontrado");Optional<RequisitoTemplateVaga> r=requisitos.buscarAtivoPorId(c.getItemId());if(!r.isPresent()||!c.getTemplateId().equals(r.get().getTemplateVagaId()))return vazio(404,"Requisito nao encontrado");r.get().setExcluidoEm(agora());requisitos.salvar(r.get());return vazio(204,"Requisito excluido");}
 public TypedResponse<VagaDTO> criarVagaAPartirDoTemplate(CriarVagaAPartirDoTemplateDTO c){if(c==null||c.getTemplateId()==null)return erroVaga(400,"Dados do template invalidos");if(!admin(c.getUsuarioSolicitanteId()))return erroVaga(403,"Acesso nao autorizado");Optional<TemplateVaga> t=templates.buscarAtivoPorId(c.getTemplateId());if(!t.isPresent())return erroVaga(404,"Template nao encontrado");Vaga v=vagas.salvar(new Vaga(t.get().getResponsavelId(),t.get().getTitulo(),t.get().getDescricao()));for(PerguntaTemplateVaga p:perguntas.listarAtivasDoTemplate(t.get().getId())){PerguntaVaga x=new PerguntaVaga();x.setVagaId(v.getId());x.setEnunciado(p.getEnunciado());x.setTipoResposta(p.getTipoResposta());x.setObrigatoria(p.isObrigatoria());x.setOrdem(p.getOrdem());perguntasVaga.salvar(x);}for(RequisitoTemplateVaga r:requisitos.listarAtivosDoTemplate(t.get().getId())){RequisitoVaga x=new RequisitoVaga();x.setVagaId(v.getId());x.setDescricao(r.getDescricao());x.setObrigatorio(r.isObrigatorio());requisitosVaga.salvar(x);}return new TypedResponse<VagaDTO>(201,"Vaga criada a partir do template",new VagaDTO(v.getId(),v.getResponsavelId(),v.getTitulo(),v.getDescricao(),v.getStatus()));}
 private boolean admin(UUID id){return id!=null&&autorizacao.podeManterTemplates(id);}private boolean invalido(String s){return s==null||s.trim().isEmpty();}private boolean perguntaInvalida(SalvarPerguntaTemplateVagaDTO c){return c.getTemplateId()==null||invalido(c.getEnunciado())||c.getTipoResposta()==null||c.getOrdem()<=0;}private boolean requisitoInvalido(SalvarRequisitoTemplateVagaDTO c){return c.getTemplateId()==null||invalido(c.getDescricao());}private OffsetDateTime agora(){return OffsetDateTime.now(clock);}private void preencher(PerguntaTemplateVaga p,SalvarPerguntaTemplateVagaDTO c){p.setTemplateVagaId(c.getTemplateId());p.setEnunciado(c.getEnunciado());p.setTipoResposta(c.getTipoResposta());p.setObrigatoria(c.isObrigatoria());p.setOrdem(c.getOrdem());}private void preencher(RequisitoTemplateVaga r,SalvarRequisitoTemplateVagaDTO c){r.setTemplateVagaId(c.getTemplateId());r.setDescricao(c.getDescricao());r.setObrigatorio(c.isObrigatorio());}
 private TypedResponse<TemplateVagaDTO> template(int s,String m,TemplateVaga t){return new TypedResponse<TemplateVagaDTO>(s,m,new TemplateVagaDTO(t.getId(),t.getResponsavelId(),t.getTitulo(),t.getDescricao()));}private TypedResponse<PerguntaTemplateVagaDTO> pergunta(int s,String m,PerguntaTemplateVaga p){return new TypedResponse<PerguntaTemplateVagaDTO>(s,m,new PerguntaTemplateVagaDTO(p.getId(),p.getEnunciado(),p.getTipoResposta(),p.isObrigatoria(),p.getOrdem()));}private TypedResponse<RequisitoTemplateVagaDTO> requisito(int s,String m,RequisitoTemplateVaga r){return new TypedResponse<RequisitoTemplateVagaDTO>(s,m,new RequisitoTemplateVagaDTO(r.getId(),r.getDescricao(),r.isObrigatorio()));}private <T> TypedResponse<T> erro(int s,String m){return new TypedResponse<T>(s,m,null);}private TypedResponse<PerguntaTemplateVagaDTO> erroPergunta(int s,String m){return erro(s,m);}private TypedResponse<RequisitoTemplateVagaDTO> erroRequisito(int s,String m){return erro(s,m);}private TypedResponse<VagaDTO> erroVaga(int s,String m){return erro(s,m);}private TypedResponse<Void> vazio(int s,String m){return new TypedResponse<Void>(s,m,null);}
}
